import { Activity, LoaderCircle, RefreshCw } from 'lucide-react'
import { useMemo, useState, type ReactNode } from 'react'
import { useNavigate } from 'react-router-dom'

import { getApiErrorMessage } from '@/api'
import { SearchableFilterSelect } from '@/components/admin/searchable-filter-select'
import { StatusBadge } from '@/components/admin/status-badge'
import { btnSecondary, cardShadow, tabGroup, tdCell, thCell } from '@/components/admin/styles'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import { useWardOptions } from '@/features/wards/hooks'
import type { WardListItem } from '@/features/wards/types'
import { PLATEAU_LGAS } from '@/lib/geography'

import { useDashboard } from '../hooks'
import type { DashboardPeriod, DashboardTrendGranularity } from '../types'
import { formatDashboardDate, initials, signedValue, toCategorySeries, toLgaSeries, toWardSeries } from '../utils'

import { DashboardEmptyState } from './dashboard-empty-state'
import { EnrollmentBarChart } from './enrollment-bar-chart'
import { EnrollmentStatusDonut } from './enrollment-status-donut'
import { EnrollmentTrendChart } from './enrollment-trend-chart'

const selectClass = 'h-10 rounded-lg border border-border bg-card px-3 text-sm font-medium text-foreground outline-none focus:border-primary'
const periods: Array<[DashboardPeriod, string]> = [['7d', 'Last 7 days'], ['30d', 'Last 30 days'], ['3m', 'Last 3 months'], ['6m', 'Last 6 months'], ['1y', 'Last year']]
const trends: Array<[DashboardTrendGranularity, string]> = [['daily', 'Daily'], ['weekly', 'Weekly'], ['monthly', 'Monthly']]

function DashboardSkeleton() {
  return <div className="flex flex-1 flex-col gap-6 p-4 sm:p-6"><div className="space-y-2"><Skeleton className="h-8 w-40" /><Skeleton className="h-4 w-full max-w-xl" /><Skeleton className="mt-5 h-10 w-full max-w-3xl" /></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }, (_, index) => <Skeleton className="h-28 rounded-xl" key={index} />)}</div><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]"><Skeleton className="h-80 rounded-xl" /><Skeleton className="h-80 rounded-xl" /></div><div className="grid gap-4 lg:grid-cols-2">{Array.from({ length: 4 }, (_, index) => <Skeleton className="h-64 rounded-xl" key={index} />)}</div></div>
}

function ClickableRow({ children, label, onClick }: { children: ReactNode; label: string; onClick: () => void }) {
  return <tr aria-label={label} className="cursor-pointer hover:bg-muted/40 focus:bg-muted/40 focus:outline-2 focus:outline-ring" onClick={onClick} onKeyDown={(event) => { if (event.key === 'Enter') onClick() }} role="link" tabIndex={0}>{children}</tr>
}

export function DashboardView() {
  const navigate = useNavigate()
  const [lga, setLga] = useState('')
  const [selectedWard, setSelectedWard] = useState<WardListItem | null>(null)
  const [wardSearch, setWardSearch] = useState('')
  const [period, setPeriod] = useState<DashboardPeriod>('30d')
  const [trend, setTrend] = useState<DashboardTrendGranularity>('monthly')
  const wardsQuery = useWardOptions(wardSearch.trim())
  const wards = useMemo(() => {
    const values = new Map<string, WardListItem>()
    for (const ward of wardsQuery.data?.pages.flatMap((page) => page.items) ?? []) if (!lga || ward.lga === lga) values.set(ward.id, ward)
    return [...values.values()]
  }, [lga, wardsQuery.data])
  const params = useMemo(() => ({ lga: lga || undefined, wardId: selectedWard?.id, period, trend }), [lga, period, selectedWard?.id, trend])
  const query = useDashboard(params)

  if (query.isPending) return <DashboardSkeleton />
  if (query.isError && !query.data) return <div className="flex flex-1 items-center justify-center p-6"><div className={`flex min-h-72 w-full max-w-2xl flex-col items-center justify-center gap-3 rounded-xl bg-card p-8 text-center ${cardShadow}`} role="alert"><p className="text-lg font-semibold">Unable to load the dashboard.</p><p className="text-sm text-muted-foreground">{getApiErrorMessage(query.error, 'Check your connection and try again.')}</p><Button onClick={() => void query.refetch()} variant="outline"><RefreshCw aria-hidden="true" /> Retry</Button></div></div>

  const data = query.data
  const kpis = [
    { label: 'Total Enrollments', value: data.kpis.totalEnrollments.value, change: data.kpis.totalEnrollments.changePercent, suffix: '%', href: '/admin/beneficiaries' },
    { label: 'Active Beneficiaries', value: data.kpis.activeBeneficiaries.value, change: data.kpis.activeBeneficiaries.changePercent, suffix: '%', href: '/admin/beneficiaries' },
    { label: 'Inactive Beneficiaries', value: data.kpis.inactiveBeneficiaries.value, change: data.kpis.inactiveBeneficiaries.changePercent, suffix: '%', inverse: true, href: '/admin/beneficiaries' },
    { label: 'New Enrollments', value: data.kpis.newEnrollments.value, change: data.kpis.newEnrollments.changePercent, suffix: '%' },
    { label: 'Total Facilities', value: data.kpis.totalFacilities.value, change: data.kpis.totalFacilities.changeAbsolute },
    { label: 'Field Workers', value: data.kpis.fieldWorkers.value, change: data.kpis.fieldWorkers.changeAbsolute },
  ]

  return <div className="flex flex-1 flex-col gap-6 p-4 sm:p-6">
    <section className="space-y-4" aria-labelledby="dashboard-title"><div><h1 className="text-2xl font-semibold tracking-[-0.48px]" id="dashboard-title">Dashboard</h1><p className="mt-1 text-sm text-muted-foreground">Monitor enrollment, coverage, facilities, field operations and programme performance.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label className="grid gap-1 text-xs font-medium text-muted-foreground">LGA<select className={selectClass} onChange={(event) => { setLga(event.target.value); setSelectedWard(null) }} value={lga}><option value="">All LGAs</option>{PLATEAU_LGAS.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><SearchableFilterSelect allLabel="All wards" emptyText={lga ? `No wards found in ${lga}.` : 'No wards found.'} hasMore={Boolean(wardsQuery.hasNextPage)} label="Ward" loading={wardsQuery.isFetching && !wardsQuery.isFetchingNextPage} loadingMore={wardsQuery.isFetchingNextPage} onLoadMore={() => void wardsQuery.fetchNextPage()} onSearchChange={setWardSearch} onSelect={(option) => { const ward = option ? wards.find((item) => item.id === option.id) ?? null : null; setSelectedWard(ward); if (ward) setLga(ward.lga) }} options={wards.map((ward) => ({ id: ward.id, label: ward.name, description: ward.lga }))} search={wardSearch} searchPlaceholder="Search wards…" value={selectedWard ? { id: selectedWard.id, label: selectedWard.name, description: selectedWard.lga } : null} /><label className="grid gap-1 text-xs font-medium text-muted-foreground">Period<select className={selectClass} onChange={(event) => setPeriod(event.target.value as DashboardPeriod)} value={period}>{periods.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="flex items-end pb-2 text-sm text-muted-foreground">Plateau State · {formatDashboardDate(data.filters.periodStart)} – {formatDashboardDate(data.filters.periodEnd)}</div></div>{wardsQuery.isError && <p className="text-sm text-destructive" role="alert">Ward options could not be loaded. You can still filter by LGA.</p>}{query.isFetching && <p className="flex items-center gap-2 text-xs text-muted-foreground" role="status"><LoaderCircle className="size-3.5 animate-spin" aria-hidden="true" /> Updating dashboard…</p>}{query.isError && query.data && <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive" role="alert"><span>The latest dashboard update failed. The previous results are still shown.</span><Button onClick={() => void query.refetch()} size="sm" variant="outline">Retry</Button></div>}</section>

    <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3" aria-label="Programme indicators">{kpis.map((item) => { const good = item.inverse ? item.change <= 0 : item.change >= 0; const card = <div className={`flex h-full flex-col gap-3 rounded-xl bg-card p-4 ${cardShadow}`}><p className="text-sm font-medium tracking-[0.28px] text-muted-foreground">{item.label}</p><div className="flex items-end gap-2"><span className="text-2xl font-semibold tracking-[-0.48px]">{item.value.toLocaleString()}</span><span className={`mb-0.5 text-sm font-semibold ${item.change === 0 ? 'text-muted-foreground' : good ? 'text-success-foreground' : 'text-destructive'}`}>{signedValue(item.change, item.suffix)}</span></div><p className="text-xs text-muted-foreground">Compared with the previous period</p></div>; return item.href ? <button className="text-left" key={item.label} onClick={() => navigate(item.href)} type="button">{card}</button> : <div key={item.label}>{card}</div> })}</section>

    <section className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]"><div className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="flex flex-wrap items-center gap-4 border-b border-border p-4"><div className="min-w-48 flex-1"><h2 className="text-sm font-semibold">Enrollment Trend</h2><p className="mt-1 text-2xl font-semibold">{data.enrollmentTrend.total.toLocaleString()} <span className="text-sm font-medium text-muted-foreground">enrollments</span></p></div><div aria-label="Enrollment trend granularity" className={tabGroup} role="tablist">{trends.map(([value, label]) => <button aria-selected={trend === value} className={`h-9 px-3 text-xs ${trend === value ? 'bg-card font-semibold text-foreground' : 'text-muted-foreground'}`} key={value} onClick={() => setTrend(value)} role="tab" type="button">{label}</button>)}</div></div><EnrollmentTrendChart average={data.enrollmentTrend.average} granularity={data.enrollmentTrend.granularity} points={data.enrollmentTrend.points} /></div><div className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Recent Activity</h2></div>{data.recentActivity.length === 0 ? <DashboardEmptyState>No recent activity is available for this period.</DashboardEmptyState> : <div className="max-h-80 divide-y divide-border overflow-y-auto">{data.recentActivity.map((item) => <div className="flex gap-3 px-4 py-3" key={item.id}><div className="mt-0.5 flex size-7 shrink-0 items-center justify-center rounded-full bg-accent text-accent-foreground"><Activity className="size-3.5" aria-hidden="true" /></div><div className="min-w-0 flex-1"><p className="text-[13px] font-medium leading-snug">{item.summary}</p><p className="mt-1 text-xs text-muted-foreground"><button className="hover:text-foreground hover:underline" onClick={() => navigate(`/admin/wards/${item.ward.id}`)} type="button">{item.ward.name}</button> · {item.actor?.name ?? 'System'} · {formatDashboardDate(item.occurredAt, true)}</p></div></div>)}</div>}</div></section>

    <section className="grid gap-4 lg:grid-cols-2"><div className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Enrollment by Category</h2></div><EnrollmentBarChart emptyText="No category data is available." items={toCategorySeries(data.enrollmentByCategory)} labelWidth={168} /></div><div className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Enrollment by Status</h2></div><EnrollmentStatusDonut breakdown={data.enrollmentByStatus} /></div></section>

    <section className="grid gap-4 lg:grid-cols-2"><div className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Enrollment by Ward</h2></div><EnrollmentBarChart emptyText="No ward enrollment data is available." items={toWardSeries(data.enrollmentByWard)} onSelect={(id) => navigate(`/admin/wards/${id}`)} /></div><div className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="flex items-center justify-between border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Enrollment by LGA</h2><button className="text-xs font-medium text-muted-foreground hover:text-foreground" onClick={() => navigate('/admin/wards')} type="button">View wards</button></div><div className="max-h-96 overflow-y-auto"><EnrollmentBarChart emptyText="No LGA enrollment data is available." items={toLgaSeries(data.enrollmentByLga)} /></div></div></section>

    <section className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="flex items-center justify-between border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Facility Overview</h2><button className="text-xs font-medium text-muted-foreground hover:text-foreground" onClick={() => navigate('/admin/facilities')} type="button">View All</button></div><div className="grid grid-cols-1 gap-4 border-b border-border p-4 sm:grid-cols-3">{[['Total Facilities', data.facilityOverview.totalFacilities], ['Active Facilities', data.facilityOverview.activeFacilities], ['Total Beneficiaries', data.facilityOverview.totalBeneficiaries]].map(([label, value]) => <div key={label}><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{Number(value).toLocaleString()}</p></div>)}</div><div className="overflow-x-auto"><table className="w-full"><thead><tr>{['Facility', 'LGA', 'Ward', 'Beneficiaries'].map((heading) => <th className={thCell} key={heading}>{heading}</th>)}</tr></thead><tbody>{data.facilityOverview.items.map((item) => <ClickableRow key={item.id} label={`View ${item.name}`} onClick={() => navigate(`/admin/facilities/${item.id}`)}><td className={`${tdCell} font-semibold`}>{item.name}</td><td className={`${tdCell} text-muted-foreground`}>{item.lga}</td><td className={`${tdCell} text-muted-foreground`}>{item.ward.name}</td><td className={`${tdCell} font-semibold`}>{item.beneficiaries.toLocaleString()}</td></ClickableRow>)}{data.facilityOverview.items.length === 0 && <tr><td className="px-4 py-10 text-center text-sm text-muted-foreground" colSpan={4}>No facilities have enrollments for this period.</td></tr>}</tbody></table></div></section>

    <section className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Field Worker Performance</h2><div className="flex flex-wrap items-center gap-2">{[['Total', data.fieldWorkerPerformance.totalFieldWorkers], ['Active', data.fieldWorkerPerformance.activeFieldWorkers], ['Enrolled', data.fieldWorkerPerformance.totalEnrolled], ['Average', data.fieldWorkerPerformance.averagePerWorker]].map(([label, value]) => <span className="rounded-lg bg-muted px-3 py-1.5 text-xs" key={label}><span className="text-muted-foreground">{label}: </span><strong>{Number(value).toLocaleString()}</strong></span>)}<button className="px-2 text-xs font-medium text-muted-foreground hover:text-foreground" onClick={() => navigate('/admin/field-workers')} type="button">View All</button></div></div><div className="overflow-x-auto"><table className="w-full"><thead><tr>{['Field Worker', 'Enrolled', 'Last Activity', 'Status'].map((heading) => <th className={thCell} key={heading}>{heading}</th>)}</tr></thead><tbody>{data.fieldWorkerPerformance.items.map((item) => <ClickableRow key={item.id} label={`View ${item.name}`} onClick={() => navigate(`/admin/field-workers/${item.id}`)}><td className={tdCell}><div className="flex items-center gap-2"><span aria-hidden="true" className="flex size-8 items-center justify-center rounded-full bg-accent text-xs font-semibold text-accent-foreground">{initials(item.name)}</span><span className="font-medium">{item.name}</span></div></td><td className={`${tdCell} font-semibold`}>{item.enrolled.toLocaleString()}</td><td className={`${tdCell} whitespace-nowrap text-muted-foreground`}>{formatDashboardDate(item.lastActivityAt, true)}</td><td className={tdCell}><StatusBadge status={item.status === 'active' ? 'Active' : 'Inactive'} /></td></ClickableRow>)}{data.fieldWorkerPerformance.items.length === 0 && <tr><td className="px-4 py-10 text-center text-sm text-muted-foreground" colSpan={4}>No field-worker activity is available for this period.</td></tr>}</tbody></table></div></section>

    <section className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="flex items-center justify-between border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Recent Enrollments</h2><button className={btnSecondary} onClick={() => navigate('/admin/beneficiaries')} type="button">View All</button></div><div className="overflow-x-auto"><table className="w-full"><thead><tr>{['Beneficiary', 'Enrollment ID', 'Category', 'LGA', 'Ward', 'Facility', 'Date', 'Status'].map((heading) => <th className={thCell} key={heading}>{heading}</th>)}</tr></thead><tbody>{data.recentEnrollments.map((item) => <ClickableRow key={item.id} label={`View ${item.beneficiaryName}`} onClick={() => navigate(`/admin/beneficiaries/${item.id}`)}><td className={`${tdCell} font-semibold`}>{item.beneficiaryName}</td><td className={`${tdCell} whitespace-nowrap font-mono text-xs text-muted-foreground`}>{item.enrollmentId}</td><td className={`${tdCell} text-muted-foreground`}>{item.category}</td><td className={`${tdCell} text-muted-foreground`}>{item.lga}</td><td className={`${tdCell} text-muted-foreground`}>{item.ward.name}</td><td className={`${tdCell} text-muted-foreground`}>{item.facility.name}</td><td className={`${tdCell} whitespace-nowrap text-muted-foreground`}>{formatDashboardDate(item.createdAt)}</td><td className={tdCell}><StatusBadge status={item.status[0].toUpperCase() + item.status.slice(1)} /></td></ClickableRow>)}{data.recentEnrollments.length === 0 && <tr><td className="px-4 py-10 text-center text-sm text-muted-foreground" colSpan={8}>No enrollments were created during this period.</td></tr>}</tbody></table></div></section>
  </div>
}
