import { Activity, LoaderCircle, RefreshCw } from 'lucide-react'
import { useMemo, useState, type ReactNode } from 'react'
import { useNavigate } from 'react-router-dom'

import { getApiErrorMessage } from '@/api'
import { SearchableFilterSelect } from '@/components/admin/searchable-filter-select'
import { StatusBadge } from '@/components/admin/status-badge'
import { btnSecondary, cardShadow, tabGroup, tdCell, thCell } from '@/components/admin/styles'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import { useWardOptions } from '@/features/wards/hooks'
import type { WardListItem } from '@/features/wards/types'
import { PLATEAU_LGAS } from '@/lib/geography'

import { useDashboard } from '../hooks'
import type { DashboardPeriod, DashboardTrendGranularity } from '../types'
import { formatDashboardDate, initials, relativeWidth, signedValue } from '../utils'

const selectClass = 'h-10 rounded-lg border border-border bg-card px-3 text-sm font-medium text-foreground outline-none focus:border-primary'
const periods: Array<[DashboardPeriod, string]> = [['7d', 'Last 7 days'], ['30d', 'Last 30 days'], ['3m', 'Last 3 months'], ['6m', 'Last 6 months'], ['1y', 'Last year']]
const trends: Array<[DashboardTrendGranularity, string]> = [['daily', 'Daily'], ['weekly', 'Weekly'], ['monthly', 'Monthly']]

function EmptyState({ children }: { children: ReactNode }) {
  return <p className="px-4 py-10 text-center text-sm text-muted-foreground">{children}</p>
}

function DashboardSkeleton() {
  return <div className="flex flex-1 flex-col gap-6 overflow-auto p-4 sm:p-6"><div className="space-y-2"><Skeleton className="h-8 w-40" /><Skeleton className="h-4 w-full max-w-xl" /><Skeleton className="mt-5 h-10 w-full max-w-3xl" /></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }, (_, index) => <Skeleton className="h-28 rounded-xl" key={index} />)}</div><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]"><Skeleton className="h-80 rounded-xl" /><Skeleton className="h-80 rounded-xl" /></div><div className="grid gap-4 lg:grid-cols-2">{Array.from({ length: 4 }, (_, index) => <Skeleton className="h-64 rounded-xl" key={index} />)}</div></div>
}

function BarList({ items, emptyText, onSelect }: { items: Array<{ id: string; label: string; count: number }>; emptyText: string; onSelect?: (id: string) => void }) {
  if (items.length === 0) return <EmptyState>{emptyText}</EmptyState>
  const maximum = Math.max(0, ...items.map((item) => item.count))
  return <div className="flex flex-col gap-3 p-4">{items.map((item) => {
    const content = <><span className="w-40 shrink-0 truncate text-left text-xs text-muted-foreground group-hover:text-foreground">{item.label}</span><div className="h-2 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${relativeWidth(item.count, maximum)}%` }} /></div><span className="w-12 text-right text-xs font-semibold">{item.count.toLocaleString()}</span></>
    return onSelect ? <button className="group flex w-full items-center gap-3 rounded-md focus-visible:outline-2 focus-visible:outline-ring" key={item.id} onClick={() => onSelect(item.id)} type="button">{content}</button> : <div className="group flex items-center gap-3" key={item.id}>{content}</div>
  })}</div>
}

function TrendChart({ points, average }: { points: Array<{ key: string; label: string; count: number }>; average: number }) {
  if (points.length === 0) return <EmptyState>No enrollment trend is available for this period.</EmptyState>
  const maximum = Math.max(1, average, ...points.map((point) => point.count))
  const chartWidth = Math.max(720, points.length * 72)
  const plotTop = 32
  const plotBottom = 276
  const plotHeight = plotBottom - plotTop
  const plotLeft = 48
  const plotRight = chartWidth - 24
  const slotWidth = (plotRight - plotLeft) / points.length
  const barWidth = Math.min(44, slotWidth * 0.55)
  const averageY = plotBottom - (average / maximum) * plotHeight
  return <div className="overflow-x-auto overflow-y-hidden p-4"><svg aria-label={`Enrollment trend with ${points.length} points and an average of ${average.toLocaleString('en-NG', { maximumFractionDigits: 1 })}`} className="h-80 w-full" role="img" style={{ minWidth: chartWidth }} viewBox={`0 0 ${chartWidth} 320`}>{Array.from({ length: 5 }, (_, index) => { const y = plotTop + (plotHeight / 4) * index; return <line className="stroke-border" key={index} strokeWidth="1" x1={plotLeft} x2={plotRight} y1={y} y2={y} /> })}<line className="stroke-success-foreground" strokeDasharray="5 5" strokeWidth="1" x1={plotLeft} x2={plotRight} y1={averageY} y2={averageY} /><rect className="fill-success" height="22" rx="4" width="88" x={plotLeft} y={Math.max(4, averageY - 25)} /><text className="fill-success-foreground text-[11px]" x={plotLeft + 6} y={Math.max(19, averageY - 10)}>Avg {average.toLocaleString('en-NG', { maximumFractionDigits: 1 })}</text>{points.map((point, index) => { const height = point.count <= 0 ? 0 : Math.max(4, (point.count / maximum) * plotHeight); const x = plotLeft + slotWidth * index + (slotWidth - barWidth) / 2; const y = plotBottom - height; return <g key={point.key}><rect className="fill-primary" height={height} rx="5" width={barWidth} x={x} y={y} /><text className="fill-muted-foreground text-[11px]" textAnchor="middle" x={x + barWidth / 2} y={Math.max(18, y - 7)}>{point.count.toLocaleString()}</text><text className="fill-muted-foreground text-[11px]" textAnchor="middle" x={x + barWidth / 2} y={plotBottom + 24}>{point.label}</text></g> })}</svg></div>
}

function ClickableRow({ children, label, onClick }: { children: ReactNode; label: string; onClick: () => void }) {
  return <tr aria-label={label} className="cursor-pointer hover:bg-muted/40 focus:bg-muted/40 focus:outline-2 focus:outline-ring" onClick={onClick} onKeyDown={(event) => { if (event.key === 'Enter') onClick() }} role="link" tabIndex={0}>{children}</tr>
}

export function DashboardView() {
  const navigate = useNavigate()
  const [lga, setLga] = useState('')
  const [selectedWard, setSelectedWard] = useState<WardListItem | null>(null)
  const [wardSearch, setWardSearch] = useState('')
  const [period, setPeriod] = useState<DashboardPeriod>('30d')
  const [trend, setTrend] = useState<DashboardTrendGranularity>('monthly')
  const wardsQuery = useWardOptions(wardSearch.trim())
  const wards = useMemo(() => {
    const values = new Map<string, WardListItem>()
    for (const ward of wardsQuery.data?.pages.flatMap((page) => page.items) ?? []) if (!lga || ward.lga === lga) values.set(ward.id, ward)
    return [...values.values()]
  }, [lga, wardsQuery.data])
  const params = useMemo(() => ({ lga: lga || undefined, wardId: selectedWard?.id, period, trend }), [lga, period, selectedWard?.id, trend])
  const query = useDashboard(params)

  if (query.isPending) return <DashboardSkeleton />
  if (query.isError && !query.data) return <div className="flex flex-1 items-center justify-center p-6"><div className={`flex min-h-72 w-full max-w-2xl flex-col items-center justify-center gap-3 rounded-xl bg-card p-8 text-center ${cardShadow}`} role="alert"><p className="text-lg font-semibold">Unable to load the dashboard.</p><p className="text-sm text-muted-foreground">{getApiErrorMessage(query.error, 'Check your connection and try again.')}</p><Button onClick={() => void query.refetch()} variant="outline"><RefreshCw aria-hidden="true" /> Retry</Button></div></div>

  const data = query.data
  const kpis = [
    { label: 'Total Enrollments', value: data.kpis.totalEnrollments.value, change: data.kpis.totalEnrollments.changePercent, suffix: '%', href: '/admin/beneficiaries' },
    { label: 'Active Beneficiaries', value: data.kpis.activeBeneficiaries.value, change: data.kpis.activeBeneficiaries.changePercent, suffix: '%', href: '/admin/beneficiaries' },
    { label: 'Inactive Beneficiaries', value: data.kpis.inactiveBeneficiaries.value, change: data.kpis.inactiveBeneficiaries.changePercent, suffix: '%', inverse: true, href: '/admin/beneficiaries' },
    { label: 'New Enrollments', value: data.kpis.newEnrollments.value, change: data.kpis.newEnrollments.changePercent, suffix: '%' },
    { label: 'Total Facilities', value: data.kpis.totalFacilities.value, change: data.kpis.totalFacilities.changeAbsolute },
    { label: 'Field Workers', value: data.kpis.fieldWorkers.value, change: data.kpis.fieldWorkers.changeAbsolute },
  ]
  const categoryMax = Math.max(0, ...data.enrollmentByCategory.map((item) => item.count))
  const statusTotal = data.enrollmentByStatus.active.count + data.enrollmentByStatus.inactive.count
  const activePercent = Math.min(100, Math.max(0, data.enrollmentByStatus.active.percent))

  return <div className="flex flex-1 flex-col gap-6 overflow-auto p-4 sm:p-6">
    <section className="space-y-4" aria-labelledby="dashboard-title"><div><h1 className="text-2xl font-semibold tracking-[-0.48px]" id="dashboard-title">Dashboard</h1><p className="mt-1 text-sm text-muted-foreground">Monitor enrollment, coverage, facilities, field operations and programme performance.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label className="grid gap-1 text-xs font-medium text-muted-foreground">LGA<select className={selectClass} onChange={(event) => { setLga(event.target.value); setSelectedWard(null) }} value={lga}><option value="">All LGAs</option>{PLATEAU_LGAS.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><SearchableFilterSelect allLabel="All wards" emptyText={lga ? `No wards found in ${lga}.` : 'No wards found.'} hasMore={Boolean(wardsQuery.hasNextPage)} label="Ward" loading={wardsQuery.isFetching && !wardsQuery.isFetchingNextPage} loadingMore={wardsQuery.isFetchingNextPage} onLoadMore={() => void wardsQuery.fetchNextPage()} onSearchChange={setWardSearch} onSelect={(option) => { const ward = option ? wards.find((item) => item.id === option.id) ?? null : null; setSelectedWard(ward); if (ward) setLga(ward.lga) }} options={wards.map((ward) => ({ id: ward.id, label: ward.name, description: ward.lga }))} search={wardSearch} searchPlaceholder="Search wards…" value={selectedWard ? { id: selectedWard.id, label: selectedWard.name, description: selectedWard.lga } : null} /><label className="grid gap-1 text-xs font-medium text-muted-foreground">Period<select className={selectClass} onChange={(event) => setPeriod(event.target.value as DashboardPeriod)} value={period}>{periods.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="flex items-end pb-2 text-sm text-muted-foreground">Plateau State · {formatDashboardDate(data.filters.periodStart)} – {formatDashboardDate(data.filters.periodEnd)}</div></div>{wardsQuery.isError && <p className="text-sm text-destructive" role="alert">Ward options could not be loaded. You can still filter by LGA.</p>}{query.isFetching && <p className="flex items-center gap-2 text-xs text-muted-foreground" role="status"><LoaderCircle className="size-3.5 animate-spin" aria-hidden="true" /> Updating dashboard…</p>}{query.isError && query.data && <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive" role="alert"><span>The latest dashboard update failed. The previous results are still shown.</span><Button onClick={() => void query.refetch()} size="sm" variant="outline">Retry</Button></div>}</section>

    <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3" aria-label="Programme indicators">{kpis.map((item) => { const good = item.inverse ? item.change <= 0 : item.change >= 0; const card = <div className={`flex h-full flex-col gap-3 rounded-xl bg-card p-4 ${cardShadow}`}><p className="text-sm font-medium tracking-[0.28px] text-muted-foreground">{item.label}</p><div className="flex items-end gap-2"><span className="text-2xl font-semibold tracking-[-0.48px]">{item.value.toLocaleString()}</span><span className={`mb-0.5 text-sm font-semibold ${item.change === 0 ? 'text-muted-foreground' : good ? 'text-success-foreground' : 'text-destructive'}`}>{signedValue(item.change, item.suffix)}</span></div><p className="text-xs text-muted-foreground">Compared with the previous period</p></div>; return item.href ? <button className="text-left" key={item.label} onClick={() => navigate(item.href)} type="button">{card}</button> : <div key={item.label}>{card}</div> })}</section>

    <section className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]"><div className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="flex flex-wrap items-center gap-4 border-b border-border p-4"><div className="min-w-48 flex-1"><h2 className="text-sm font-semibold">Enrollment Trend</h2><p className="mt-1 text-2xl font-semibold">{data.enrollmentTrend.total.toLocaleString()} <span className="text-sm font-medium text-muted-foreground">enrollments</span></p></div><div className={tabGroup}>{trends.map(([value, label]) => <button className={`h-9 px-3 text-xs ${trend === value ? 'bg-card font-semibold text-foreground' : 'text-muted-foreground'}`} key={value} onClick={() => setTrend(value)} type="button">{label}</button>)}</div></div><TrendChart average={data.enrollmentTrend.average} points={data.enrollmentTrend.points} /></div><div className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Recent Activity</h2></div>{data.recentActivity.length === 0 ? <EmptyState>No recent activity is available for this period.</EmptyState> : <div className="max-h-80 divide-y divide-border overflow-y-auto">{data.recentActivity.map((item) => <div className="flex gap-3 px-4 py-3" key={item.id}><div className="mt-0.5 flex size-7 shrink-0 items-center justify-center rounded-full bg-accent text-accent-foreground"><Activity className="size-3.5" aria-hidden="true" /></div><div className="min-w-0 flex-1"><p className="text-[13px] font-medium leading-snug">{item.summary}</p><p className="mt-1 text-xs text-muted-foreground"><button className="hover:text-foreground hover:underline" onClick={() => navigate(`/admin/wards/${item.ward.id}`)} type="button">{item.ward.name}</button> · {item.actor?.name ?? 'System'} · {formatDashboardDate(item.occurredAt, true)}</p></div></div>)}</div>}</div></section>

    <section className="grid gap-4 lg:grid-cols-2"><div className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Enrollment by Category</h2></div>{data.enrollmentByCategory.length === 0 ? <EmptyState>No category data is available.</EmptyState> : <div className="flex flex-col gap-3 p-4">{data.enrollmentByCategory.map((item) => <div className="flex items-center gap-3" key={item.category}><span className="w-44 shrink-0 truncate text-xs text-muted-foreground" title={item.category}>{item.category}</span><div className="h-2 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${relativeWidth(item.count, categoryMax)}%` }} /></div><span className="w-12 text-right text-xs font-semibold">{item.count.toLocaleString()}</span></div>)}</div>}</div><div className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Enrollment by Status</h2></div><div className="grid gap-5 p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div className="space-y-4"><div className="flex items-center gap-3"><span className="w-16 text-xs text-muted-foreground">Active</span><div className="h-2 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${activePercent}%` }} /></div><span className="w-28 text-right text-xs font-semibold">{data.enrollmentByStatus.active.count.toLocaleString()} ({data.enrollmentByStatus.active.percent.toLocaleString()}%)</span></div><div className="flex items-center gap-3"><span className="w-16 text-xs text-muted-foreground">Inactive</span><div className="h-2 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-destructive" style={{ width: `${Math.min(100, Math.max(0, data.enrollmentByStatus.inactive.percent))}%` }} /></div><span className="w-28 text-right text-xs font-semibold">{data.enrollmentByStatus.inactive.count.toLocaleString()} ({data.enrollmentByStatus.inactive.percent.toLocaleString()}%)</span></div></div><div className="relative mx-auto size-24"><svg aria-label={`${data.enrollmentByStatus.active.percent}% active and ${data.enrollmentByStatus.inactive.percent}% inactive`} className="size-24 -rotate-90" role="img" viewBox="0 0 36 36"><circle className="stroke-muted" cx="18" cy="18" fill="transparent" r="15.9" strokeWidth="4" /><circle className="stroke-primary" cx="18" cy="18" fill="transparent" r="15.9" strokeDasharray={`${activePercent} ${100 - activePercent}`} strokeWidth="4" /></svg><span className="absolute inset-0 flex items-center justify-center text-xs font-semibold">{statusTotal.toLocaleString()}</span></div></div></div></section>

    <section className="grid gap-4 lg:grid-cols-2"><div className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Enrollment by Ward</h2></div><BarList emptyText="No ward enrollment data is available." items={data.enrollmentByWard.map((item) => ({ id: item.wardId, label: item.name, count: item.count }))} onSelect={(id) => navigate(`/admin/wards/${id}`)} /></div><div className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="flex items-center justify-between border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Enrollment by LGA</h2><button className="text-xs font-medium text-muted-foreground hover:text-foreground" onClick={() => navigate('/admin/wards')} type="button">View wards</button></div><div className="max-h-96 overflow-y-auto"><BarList emptyText="No LGA enrollment data is available." items={data.enrollmentByLga.map((item) => ({ id: item.lga, label: item.lga, count: item.count }))} /></div></div></section>

    <section className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="flex items-center justify-between border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Facility Overview</h2><button className="text-xs font-medium text-muted-foreground hover:text-foreground" onClick={() => navigate('/admin/facilities')} type="button">View All</button></div><div className="grid grid-cols-1 gap-4 border-b border-border p-4 sm:grid-cols-3">{[['Total Facilities', data.facilityOverview.totalFacilities], ['Active Facilities', data.facilityOverview.activeFacilities], ['Total Beneficiaries', data.facilityOverview.totalBeneficiaries]].map(([label, value]) => <div key={label}><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{Number(value).toLocaleString()}</p></div>)}</div><div className="overflow-x-auto"><table className="w-full"><thead><tr>{['Facility', 'LGA', 'Ward', 'Beneficiaries'].map((heading) => <th className={thCell} key={heading}>{heading}</th>)}</tr></thead><tbody>{data.facilityOverview.items.map((item) => <ClickableRow key={item.id} label={`View ${item.name}`} onClick={() => navigate(`/admin/facilities/${item.id}`)}><td className={`${tdCell} font-semibold`}>{item.name}</td><td className={`${tdCell} text-muted-foreground`}>{item.lga}</td><td className={`${tdCell} text-muted-foreground`}>{item.ward.name}</td><td className={`${tdCell} font-semibold`}>{item.beneficiaries.toLocaleString()}</td></ClickableRow>)}{data.facilityOverview.items.length === 0 && <tr><td className="px-4 py-10 text-center text-sm text-muted-foreground" colSpan={4}>No facilities have enrollments for this period.</td></tr>}</tbody></table></div></section>

    <section className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Field Worker Performance</h2><div className="flex flex-wrap items-center gap-2">{[['Total', data.fieldWorkerPerformance.totalFieldWorkers], ['Active', data.fieldWorkerPerformance.activeFieldWorkers], ['Enrolled', data.fieldWorkerPerformance.totalEnrolled], ['Average', data.fieldWorkerPerformance.averagePerWorker]].map(([label, value]) => <span className="rounded-lg bg-muted px-3 py-1.5 text-xs" key={label}><span className="text-muted-foreground">{label}: </span><strong>{Number(value).toLocaleString()}</strong></span>)}<button className="px-2 text-xs font-medium text-muted-foreground hover:text-foreground" onClick={() => navigate('/admin/field-workers')} type="button">View All</button></div></div><div className="overflow-x-auto"><table className="w-full"><thead><tr>{['Field Worker', 'Enrolled', 'Last Activity', 'Status'].map((heading) => <th className={thCell} key={heading}>{heading}</th>)}</tr></thead><tbody>{data.fieldWorkerPerformance.items.map((item) => <ClickableRow key={item.id} label={`View ${item.name}`} onClick={() => navigate(`/admin/field-workers/${item.id}`)}><td className={tdCell}><div className="flex items-center gap-2"><span aria-hidden="true" className="flex size-8 items-center justify-center rounded-full bg-accent text-xs font-semibold text-accent-foreground">{initials(item.name)}</span><span className="font-medium">{item.name}</span></div></td><td className={`${tdCell} font-semibold`}>{item.enrolled.toLocaleString()}</td><td className={`${tdCell} whitespace-nowrap text-muted-foreground`}>{formatDashboardDate(item.lastActivityAt, true)}</td><td className={tdCell}><StatusBadge status={item.status === 'active' ? 'Active' : 'Inactive'} /></td></ClickableRow>)}{data.fieldWorkerPerformance.items.length === 0 && <tr><td className="px-4 py-10 text-center text-sm text-muted-foreground" colSpan={4}>No field-worker activity is available for this period.</td></tr>}</tbody></table></div></section>

    <section className={`overflow-hidden rounded-xl bg-card ${cardShadow}`}><div className="flex items-center justify-between border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Recent Enrollments</h2><button className={btnSecondary} onClick={() => navigate('/admin/beneficiaries')} type="button">View All</button></div><div className="overflow-x-auto"><table className="w-full"><thead><tr>{['Beneficiary', 'Enrollment ID', 'Category', 'LGA', 'Ward', 'Facility', 'Date', 'Status'].map((heading) => <th className={thCell} key={heading}>{heading}</th>)}</tr></thead><tbody>{data.recentEnrollments.map((item) => <ClickableRow key={item.id} label={`View ${item.beneficiaryName}`} onClick={() => navigate(`/admin/beneficiaries/${item.id}`)}><td className={`${tdCell} font-semibold`}>{item.beneficiaryName}</td><td className={`${tdCell} whitespace-nowrap font-mono text-xs text-muted-foreground`}>{item.enrollmentId}</td><td className={`${tdCell} text-muted-foreground`}>{item.category}</td><td className={`${tdCell} text-muted-foreground`}>{item.lga}</td><td className={`${tdCell} text-muted-foreground`}>{item.ward.name}</td><td className={`${tdCell} text-muted-foreground`}>{item.facility.name}</td><td className={`${tdCell} whitespace-nowrap text-muted-foreground`}>{formatDashboardDate(item.createdAt)}</td><td className={tdCell}><StatusBadge status={item.status[0].toUpperCase() + item.status.slice(1)} /></td></ClickableRow>)}{data.recentEnrollments.length === 0 && <tr><td className="px-4 py-10 text-center text-sm text-muted-foreground" colSpan={8}>No enrollments were created during this period.</td></tr>}</tbody></table></div></section>
  </div>
}
