export type {
  CreateHealthFacilityPayload,
  DeleteHealthFacilityResult,
  HealthFacilityActivityAction,
  HealthFacilityActivityCategory,
  HealthFacilityActivityEntry,
  HealthFacilityBatchError,
  HealthFacilityBatchResult,
  HealthFacilityCapitation,
  HealthFacilityCapitationApi,
  HealthFacilityCapitationRecord,
  HealthFacilityCapitationRecordApi,
  HealthFacilityDetail,
  HealthFacilityDetailApi,
  HealthFacilityDetailStats,
  HealthFacilityDetailStatsApi,
  HealthFacilityLevel,
  HealthFacilityListItem,
  HealthFacilityListItemApi,
  HealthFacilityListParams,
  HealthFacilityListResult,
  HealthFacilityListSummary,
  HealthFacilityRecord,
  HealthFacilityStatus,
  HealthFacilityWard,
  UpdateHealthFacilityPayload,
  UpdateHealthFacilityVariables,
} from './facility.types'
